### PR TITLE
New model for codec instances (work in progress)

### PR DESCRIPTION
**Pull request by travisbrown**
This is still messy and undocumented, but I wanted to post it for comparison with the older approach.

I fixed the tests for `scodec`, but not `core`, and not the benchmarks.

### CODE REVIEW

**Comment by vkostyukov** [comment]
Looks fantastic! :+1:

**Comment by vkostyukov** [comment]
Do you mind to merge this so I can start working on benchmarks?

**Comment by travisbrown** [comment]
Don't mind, that sounds good to me, thanks. I'm going to polish the exception encoding business a bit and then start on expanding the tests (unless you have other ideas?).

**Comment by vkostyukov** [comment]
I'm going to kill pickling stuff and continue working on benchmarks.

**Pull request merged**
