### PR TITLE
Add serial-benchmark

### PR DESCRIPTION
**Pull request by vkostyukov**
Use JMH to benchmark Finagle Serial. This is a sketch, but it works. I'm going to continue working on it. The current results on a small data for pickling:

```
[info] Benchmark                                       Mode  Samples   Score   Error  Units
[info] i.g.f.s.SmallPicklingBenchmark.testSmall10     thrpt       20  37.377 ± 3.990  ops/s
[info] i.g.f.s.SmallPicklingBenchmark.testSmall100    thrpt       20   3.579 ± 0.499  ops/s
```

### CODE REVIEW

**Comment by travisbrown** [comment]
I like the setup! This seems pretty slow, though. Any idea off the top of your head how it compares with e.g. thrift-mux?

**Comment by vkostyukov** [comment]
Yeah. I'm pretty sure it's going to be faster for thrift-mux. Let's see what scodec is like.

**Comment by vkostyukov** [comment]
Don'/t you mind if I merge this?

**Comment by travisbrown** [comment]
:+1:

**Pull request merged**
