### PR TITLE
Thriftmux benchmark

### PR DESCRIPTION
**Pull request by travisbrown**
This needs some clean-up, and it only works on 2.10 (I think because of an issue with Scrooge), but the preliminary results are interesting:

```
i.g.f.s.RoundTripThriftSmallBenchmark.test    thrpt       20  21221.289 ± 483.478  ops/s
i.g.f.s.ScodecSmallRTBenchmark.test           thrpt       20   8607.848 ± 244.856  ops/s
```

I.e. Scodec manages about 40% of the throughput of Thrift, which is better than I expected.

### CODE REVIEW

**Comment by vkostyukov** [comment]
Looks very interesting! Do we consider Thrift implementation as a gold one (a theoretical possible maxim throughput)? I think it's pretty good result for scodec, consider that it requires less boilerplate and configurations (and usually works with zero-config).

**Comment by travisbrown** [comment]
It's probably close, but I think more importantly it's the most likely alternative that people would be using (assuming they're using Finagle).

**Comment by travisbrown** [comment]
Rebased against update in #23.

**Comment by travisbrown** [comment]
(Also worth noting that the Thrift benchmark uses the `Small` generated by Scrooge, not the user-defined `Small`.)

**Pull request merged**
