### PR TITLE
Turn on and configure test coverage reporting

### PR DESCRIPTION
**Pull request by travisbrown**

### CODE REVIEW

**Comment by vkostyukov** [comment]
Are we going to add coveralls badge?

```
[![Coverage Status](https://coveralls.io/repos/finagle/finagle-serial/badge.svg)](https://coveralls.io/r/finagle/finagle-serial)
```

**Comment by travisbrown** [comment]
I wanted to be sure the integration tests were showing up in the Coveralls reporting numbers (they aren't). I'm planning to try to figure out why a little later this afternoon.

**Comment by vkostyukov** [comment]
Oh, ok. Looks good to me :+1:

**Comment by travisbrown** [comment]
This is green after a lot of fussing, and the coverage number now includes integration tests. I've added a Coveralls badge.

Note that I've turned off Travis's container-based builds, since for the past couple of days (at least) it's been failing to download artifacts from Sonatype's snapshot repo, and in general it seems much flakier than the default.

**Pull request merged**
